//This manual tests use RestClient vsCode Extension 
//these file is just for testing purposes, and is not related with the code itself

###GET DEVICE LIST
GET http://localhost:3000/devices

###GET DEVICE BY ID
GET http://localhost:3000/devices/Th3ngERn9

###DELETE DEVICE BY ID
DELETE http://localhost:3000/devices/sstEsXXMK

###POST DEVICE
POST http://localhost:3000/devices
Content-Type: application/json

{
    "system_name": "DESKTOP-ONE2",
    "type": "WINDOWS",
    "hdd_capacity": "92"
}

###POST DEVICE
PUT http://localhost:3000/devices/JvHxqyVfs
Content-Type: application/json

{
    "system_name": "DESKTOP-ONE2",
    "type": "MAC",
    "hdd_capacity": "100"
}